In [1]:
# general
import pandas as pd
import numpy as np
import data_cleaner as dc # self-written
# ML & DL:
import sklearn
import torch
import torch.nn as nn
import torch.nn.functional as F
# from tab_transformer_pytorch import FTTransformer
import rtdl
import zero
from rtdl import FTTransformer
# self-written
import DL_functions as dl
from importlib import reload
reload(dl)

<module 'DL_functions' from '/Users/tsung_macbook/Dropbox/DL/final/code/DL_functions.py'>

In [2]:
# Default model result:
model, _, _ = dl.default_setup()
default_model = torch.load("output/FTT_default_model_3cv.pt", map_location="cpu")
# for i in range(1,4):
i = "1"
model.load_state_dict(default_model[i]["best_bac_wts"])
print("Testing set result: ")
test_result = dl.model_evaluation(model)
print("Training set result: ")
train_result = dl.model_evaluation(model, set="train")


Testing set result: 
One vs. one weighted AUC: 0.9359356147201424
One vs. one macro AUC: 0.9357719463226031
One vs. all weighted AUC: 0.9192691601196131
One vs. all macro AUC: 0.9500356322202504
Acc in each class: [0.8187702265372169, 0.6, 0.24, 0.9230769230769231, 0.7894736842105263, 0.6764705882352942]
[[506  29  14  16  10  43]
 [ 11  33   9   0   0   2]
 [  3  16   6   0   0   0]
 [  2   0   0  36   0   1]
 [  5   0   0   0  30   3]
 [ 14   0   0   0   8  46]]
{'ACC': 0.7794, 'BAC': 0.6746, 'macroF1': 0.6075, 'One vs. one macroAUC': 0.95}
Training set result: 
One vs. one weighted AUC: 0.9794373076730677
One vs. one macro AUC: 0.9757780723304639
One vs. all weighted AUC: 0.9773408613157676
One vs. all macro AUC: 0.9830692387995352
Acc in each class: [0.8892371995820272, 0.8433734939759037, 0.5348837209302325, 1.0, 0.9245283018867925, 0.912621359223301]
[[851  37  14  16  16  23]
 [  4  70   8   0   0   1]
 [  4  14  23   0   0   2]
 [  0   0   0  73   0   0]
 [  3   0   0   0  49  

In [3]:
# Optimized model result:
model, _, _ = dl.default_setup()
optimized_model = torch.load("output/FTT_optimized_3cv_500iter.pt", map_location="cpu")
# for i in range(1,4):
i = str(i)
model.load_state_dict(optimized_model[i]["best_bac_wts"])
print("Testing set result: ")
test_result = dl.model_evaluation(model)
print("Training set result: ")
train_result = dl.model_evaluation(model, set="train")

Testing set result: 
One vs. one weighted AUC: 0.9481731793642953
One vs. one macro AUC: 0.9466882348114456
One vs. all weighted AUC: 0.933966300086029
One vs. all macro AUC: 0.9579713397375786
Acc in each class: [0.8171521035598706, 0.43636363636363634, 0.72, 0.8974358974358975, 0.8157894736842105, 0.7205882352941176]
[[505  19  31   6  19  38]
 [ 10  24  21   0   0   0]
 [  0   7  18   0   0   0]
 [  4   0   0  35   0   0]
 [  3   0   0   0  31   4]
 [ 11   0   0   0   8  49]]
{'ACC': 0.7853, 'BAC': 0.7346, 'macroF1': 0.6418, 'One vs. one macroAUC': 0.958}
Training set result: 
One vs. one weighted AUC: 0.994952296673518
One vs. one macro AUC: 0.9967298463496734
One vs. all weighted AUC: 0.9934706555854512
One vs. all macro AUC: 0.9945281333986569
Acc in each class: [0.9080459770114943, 0.6626506024096386, 1.0, 1.0, 1.0, 0.9902912621359223]
[[869  29  37   0   8  14]
 [  1  55  27   0   0   0]
 [  0   0  43   0   0   0]
 [  0   0   0  73   0   0]
 [  0   0   0   0  53   0]
 [  1   0 

In [25]:
# normalized evaluation
model, _, _ = dl.default_setup()
optimized_model = torch.load("output/FTT_optimized_3cv_normalized.pt", map_location="cpu")
for i in range(1,4):
    i = str(i)
    model.load_state_dict(optimized_model[i]["best_bac_wts"])
    result = dl.test_evaluation(model, normalize=True)
    print(result)

{'ACC': 0.7841043890865955, 'BAC': 0.6921937016764034, 'macroF1': 0.6047396156057742, 'CM': array([[497,  45,   6,  16,  11,  43],
       [  7,  42,   6,   0,   0,   0],
       [  4,  19,   2,   0,   0,   0],
       [  1,   0,   0,  38,   0,   0],
       [  5,   0,   0,   0,  28,   5],
       [  8,   1,   0,   0,   5,  54]])}
{'ACC': 0.7924080664294187, 'BAC': 0.5583568915045665, 'macroF1': 0.583885602627011, 'CM': array([[556,  21,  12,   6,   1,  22],
       [ 23,  20,  12,   0,   0,   0],
       [ 11,   8,   6,   0,   0,   0],
       [  7,   0,   0,  32,   0,   0],
       [ 15,   0,   0,   0,  20,   3],
       [ 31,   1,   0,   0,   2,  34]])}
{'ACC': 0.797153024911032, 'BAC': 0.6165519119733253, 'macroF1': 0.6016130147735038, 'CM': array([[539,  15,  14,   8,   9,  33],
       [ 20,  24,  11,   0,   0,   0],
       [ 10,   9,   5,   0,   0,   1],
       [  4,   0,   0,  35,   0,   0],
       [ 10,   0,   0,   0,  24,   4],
       [ 17,   1,   0,   0,   5,  45]])}
